config/routes.rb
Rails.application.routes.draw do
  resources :payment_notifications

  devise_for :profiles, controllers: {
        sessions: 'profiles/sessions'
      }

  root 'tryouts#index'

get 'confirm' => 'tryouts#confirm', as: :tryouts_confirm

resources :tryouts do
  resources :players
end

resources :coaches do
  resources :evaluations
end
  resources :guardianships
  resources :evaluations
  resources :guardians
  resources :coaches
  resources :players

  resources :tryouts do
    member do
get 'confirm' => 'tryouts#confirm'

    end
 end

  resources :tryouts do
    resources :player_tryouts
  end

  resources :player_tryouts do
    resources :players
  end

  resources :player_tryouts

end

app/models/coach.rb
class Coach < Profile
  has_many :evaluations
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  before_action :set_coach, only: [:show, :edit, :destroy, :update]

  # GET /coaches
  # GET /coaches.json
  def index
    @coaches = Coach.all
  end

  # GET /coaches/1
  # GET /coaches/1.json
  def show
  end

  # GET /coaches/new
  def new
    @coach = Coach.new
  end

  # GET /coaches/1/edit
  def edit
  end

  # POST /coaches
  # POST /coaches.json
  def create
    @coach = Coach.new(coach_params)

    respond_to do |format|
      if @coach.save
        format.html { redirect_to @coach, notice: 'Coach was successfully created.' }
        format.json { render :show, status: :created, location: @coach }
      else
        format.html { render :new }
        format.json { render json: @coach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coaches/1
  # PATCH/PUT /coaches/1.json
  def update
    respond_to do |format|
      if @coach.update(coach_params)
        format.html { redirect_to tryouts_path, notice: 'Coach was successfully updated.' }
        format.json { render :show, status: :ok, location: @coach }
      else
        format.html { render :edit }
        format.json { render json: @coach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coaches/1
  # DELETE /coaches/1.json
  def destroy
    @coach.destroy
    respond_to do |format|
      format.html { redirect_to coaches_url, notice: 'Coach was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coach
      @coach = Coach.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coach_params
      params.require(:coach).permit(:type, :first_name, :last_name, :email, :phone, :profile_id)
    end
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/views/coaches/_form.html.erb
<%= form_for(@coach) do |f| %>
  <% if @coach.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coach.errors.count, "error") %> prohibited this coach from being saved:</h2>

      <ul>
      <% @coach.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
      <div class="col-md-12">
        <h3><u>Demographic Information</u>:</h3>
          <p>
            <strong>ID:</strong>
            <%= @coach.id %>
          </p>
        <div class="field">
          <%= f.label :type %><br>
          <%= f.select(:type, ['Player', 'Coach'], class:'form-control') %>
        </div>
        <div class="field">
          <%= f.label :first_name, 'First Name:' %><br>
          <%= f.text_field :first_name, class: 'form-control' %>
        </div>
        <div class="field">
          <%= f.label :last_name, 'Last Name:' %><br>
          <%= f.text_field :last_name, class: 'form-control' %>
        </div>
        <div class="field">
          <%= f.label :email, 'Email:' %><br>
          <%= f.text_field :email, class: 'form-control' %>
        </div>
        <div class="field">
          <%= f.label :phone, 'Phone:' %><br>
          <%= f.number_field :phone, class: 'form-control' %>
        </div>
  <hr>
    <div class="row">
      <div class="col-md-12">
        <div class="actions">
          <%= f.submit 'Submit', class: 'btn btn-primary pull-right' %>
        </div>
      </div>
    </div>
<% end %>

app/views/coaches/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>Edit Coach</h1>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/coaches/index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>Coaches <%= link_to 'New Coach', new_coach_path, class: 'btn btn-success pull-right', style: 'color:white' %></h1>
  </div>
  <div class="panel-body">
    <table class="table table-hover table-striped table-responsive">
      <thead>
      <tr>
        <th>ID</th>
        <th>Type</th>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th></th>
      </tr>
      </thead>

      <tbody>
      <% @coaches.each do |coach| %>
          <tr>
	          <td><%= coach.id %></td>
            <td><%= coach.type %></td>
            <td><%= link_to coach.first_name.to_s + ' ' + coach.last_name.to_s, coach_path(coach) %></td>
            <td><%= coach.email %></td>
            <td><%= coach.phone %></td>
            <td><%= link_to 'Details', coach_path(coach), class: 'btn btn-default' %></td>
            <td><%= link_to 'Edit Coach', edit_coach_path(coach), class: 'btn btn-info' %></td>
            <td><%= link_to 'Delete', coach, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger pull-right', style: 'color:white' %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <br>


  </div>
</div>

app/views/coaches/new.html.erb
<h1>New Coach</h1>

<%= render 'form' %>

<%= link_to 'Back', coaches_path %>

app/views/coaches/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3>Coach Information: <u><%= link_to @coach.first_name + ' ' + @coach.last_name, edit_coach_path(@coach), style:'color:white' %></u> <%= link_to 'Edit', edit_coach_path(@coach), class:'btn btn-default pull-right' %></h3>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-6">
        <p>
          <strong>Email:</strong>
          <%= @coach.email %>
        </p>

        <p>
          <strong>Phone:</strong>
          <%= @coach.phone %>
        </p>
      </div>
    </div>
  </div>
</div>